sonar.organization=rahul-chavan-mourah
sonar.projectKey=rahul-chavan-mourah_liveproject
# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.java.binaries=.
